server:
  port: 8089
  servlet:
    context-path: /
spring:
  datasource:
    name: xdzs
    url: jdbc:mysql://139.196.75.14:3306/xdzs
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 39.97.112.80
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 9
        max-wait: -1
        min-idle: 0
    timeout: 1000
mybatis:
  type-aliases-package: com.softlab.common.model
  mapper-locations: classpath:mapper/*Mapper.xml
